version: '3.8'
services:
  app:
    build: .
    container_name: telegram_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://secret:secret@db:5432/postgres
    volumes:
      - .:/app
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres_telegram_api
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge